version: '3'

services:
  spring-boot-prod-docker-app:
    image: spring-boot-prod-app-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:9000
    environment:
      - SPRING_PROFILES_ACTIVE=dev
